{% set name = "lightweight-mmm" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/{{ name.replace('-', '_') }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3e82b076400cd00eda80be20f23d4a1e3b6192846fbc6d9151d3155f61aeac13
  patches:
    - 0001-increase-mathplot-version.patch

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  # Supported versions
  # https://github.com/google/lightweight_mmm/blob/v0.1.9/setup.py#L74
  skip: True # [py<310 or py>=311 or s390x]
  

requirements:
  build: 
    - patch # [not win]
    - m2-patch  # [win]
    - clang # [win]
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - absl-py
    - arviz >=0.11.2
    - immutabledict >=2.0.0
    - jax >=0.3.18
    - jaxlib >=0.3.18
    # matplotlib-base ==3.6.1 in the requirements but not avaliable in conda main channel.
    - matplotlib-base ==3.6.2
    - numpy >=1.23
    - numpyro >=0.9.2
    - pandas >=1.1.5
    - scipy
    - seaborn ==0.11.1
    - scikit-learn
    - statsmodels >=0.13.0
    - tensorflow >=2.7.2

test:
  imports:
    - lightweight_mmm
  commands:
    - pip check
    - pytest -v lightweight_mmm
  requires:
    - pip
    - pytest
    - setuptools

about:
  home: https://github.com/google/lightweight_mmm
  summary: Package for Media-Mix-Modelling
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/google/lightweight_mmm/tree/v0.1.9
  doc_url: https://lightweight-mmm.readthedocs.io/
  description: LMMM is a python library that helps organisations understand and optimise marketing spend across media channels.

extra:
  recipe-maintainers:
    - snegireff
