{% set name = "lightweight-mmm" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lightweight_mmm-{{ version }}.tar.gz
  sha256: 3f6562476f08dc30e10bdee569784782edaf79724ee34b64a525ce55e2fbf01c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - absl-py
    - arviz >=0.11.2
    - immutabledict >=2.0.0
    - jax >=0.3.18
    - jaxlib >=0.3.18
    - matplotlib-base ==3.6.1
    - numpy >=1.23
    - numpyro >=0.9.2
    - pandas >=1.1.5
    - scipy
    - seaborn ==0.11.1
    - scikit-learn
    - statsmodels >=0.13.0
    - tensorflow >=2.7.2

test:
  imports:
    - lightweight_mmm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/lightweight_mmm
  summary: Package for Media-Mix-Modelling
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - snegireff
